
apiVersion: v1
kind: Namespace
metadata:
  name: demo

---

apiVersion: v1
kind: Namespace
metadata:
  name: agent

---

apiVersion: v1
kind: Namespace
metadata:
  name: worker
  
---

apiVersion: v1
kind: Service
metadata:
  name: main-service
  namespace: demo
spec:
  type: ClusterIP
  selector:
    app: main-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-server
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-server
  template:
    metadata:
      name: main-server
      labels:
        app: main-server
    spec:
      tolerations:
      - key: "task"
        operator: "Equal"
        value: "demo"
        effect: "NoSchedule"
      containers:
      - name: main-server
        image: 702230020526.dkr.ecr.eu-central-1.amazonaws.com/main-server:latest
        resources:
          limits:
            cpu: 1000m
            memory: 2048Mi
          requests:
            cpu: 250m
            memory: 512Mi
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Development"
          - name: ASPNETCORE_PORT
            value: "8080"
          - name: ASPNETCORE_K8_URL
            value: ""
          - name: ASPNETCORE_TOKEN
            value: ""
          - name: ASPNETCORE_AGENT_IMAGE
            value: "702230020526.dkr.ecr.eu-central-1.amazonaws.com/agent"
          - name: ASPNETCORE_HOST
            value: "main-service.demo"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 20
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 30
